# conexao
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.PostgreSQLDialectct