spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

api:
  security:
    token:
      secret: 12345678